name: admission_lottery
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cross_scroll: ^0.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  excel: ^4.0.6
  file_picker: ^8.1.4
  fluent_ui: ^4.13.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  path_provider: ^2.1.1
  pdf: ^3.10.6
  win_toast: ^0.4.0

dependency_overrides:
  archive: ^3.6.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
